/** German labels for shop product technical data (Dato field api keys in camelCase). */
export const PRODUCT_TECHNICAL_FIELDS = [
  { key: 'dimmable', label: 'Dimmbar', type: 'boolean' as const },
  { key: 'heightAdjustable', label: 'Höhenverstellbar', type: 'boolean' as const },
  { key: 'batteryOperated', label: 'Akkubetrieben', type: 'boolean' as const },
  { key: 'swivelable', label: 'Schwenkbar', type: 'boolean' as const },
  { key: 'switchIntegrated', label: 'Schalter integriert', type: 'boolean' as const },
  { key: 'power', label: 'Leistung', type: 'string' as const },
  { key: 'brightness', label: 'Helligkeit', type: 'string' as const },
  { key: 'lightColor', label: 'Lichtfarbe', type: 'string' as const },
  { key: 'lightDistribution', label: 'Lichtverteilung', type: 'string' as const },
  { key: 'protectionFactor', label: 'Schutzfaktor', type: 'string' as const },
  { key: 'protectionClass', label: 'Schutzklasse', type: 'string' as const },
  { key: 'input', label: 'Input', type: 'string' as const },
  { key: 'output', label: 'Output', type: 'string' as const },
  { key: 'chargerIncluded', label: 'Ladegerät', type: 'string' as const },
  { key: 'size', label: 'Grösse', type: 'string' as const },
  { key: 'height', label: 'Höhe', type: 'string' as const },
  { key: 'overallHeight', label: 'Gesamthöhe', type: 'string' as const },
  { key: 'length', label: 'Länge', type: 'string' as const },
  { key: 'width', label: 'Breite', type: 'string' as const },
  { key: 'depth', label: 'Tiefe', type: 'string' as const },
  { key: 'diameter', label: 'Durchmesser', type: 'string' as const },
  { key: 'dimensions', label: 'Masse', type: 'string' as const },
  { key: 'reach', label: 'Ausladung', type: 'string' as const },
  { key: 'colors', label: 'Farben', type: 'string' as const },
  { key: 'metalColors', label: 'Metallfarben', type: 'string' as const },
  { key: 'fabricColors', label: 'Stofffarben', type: 'string' as const },
  { key: 'glass', label: 'Glas', type: 'string' as const },
  { key: 'crystal', label: 'Kristall', type: 'string' as const },
  { key: 'shade', label: 'Lampenschirm', type: 'string' as const },
  { key: 'cover', label: 'Bezug', type: 'string' as const },
  { key: 'lowerCover', label: 'Untere Abdeckung', type: 'string' as const },
  { key: 'basePlate', label: 'Bodenplatte', type: 'string' as const },
  { key: 'head', label: 'Leuchtenkopf', type: 'string' as const },
  { key: 'profile', label: 'Profil', type: 'string' as const },
  { key: 'material', label: 'Material', type: 'string' as const },
  { key: 'mounting', label: 'Halterung', type: 'string' as const },
  { key: 'showroomNote', label: 'Showroom', type: 'string' as const },
] as const;

export type ProductTechnicalFieldKey = (typeof PRODUCT_TECHNICAL_FIELDS)[number]['key'];
